# Generated by Django 4.1.1 on 2023-05-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_case_file01_alter_case_file02_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
